// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package collector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadTracker returns the embedded CollectionSpec for Tracker.
func LoadTracker() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TrackerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Tracker: %w", err)
	}

	return spec, err
}

// LoadTrackerObjects loads Tracker and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TrackerObjects
//	*TrackerPrograms
//	*TrackerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTrackerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTracker()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TrackerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TrackerSpecs struct {
	TrackerProgramSpecs
	TrackerMapSpecs
	TrackerVariableSpecs
}

// TrackerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TrackerProgramSpecs struct {
	TraceWrite *ebpf.ProgramSpec `ebpf:"trace_write"`
}

// TrackerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TrackerMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// TrackerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TrackerVariableSpecs struct {
}

// TrackerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type TrackerObjects struct {
	TrackerPrograms
	TrackerMaps
	TrackerVariables
}

func (o *TrackerObjects) Close() error {
	return _TrackerClose(
		&o.TrackerPrograms,
		&o.TrackerMaps,
	)
}

// TrackerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type TrackerMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *TrackerMaps) Close() error {
	return _TrackerClose(
		m.Events,
	)
}

// TrackerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type TrackerVariables struct {
}

// TrackerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type TrackerPrograms struct {
	TraceWrite *ebpf.Program `ebpf:"trace_write"`
}

func (p *TrackerPrograms) Close() error {
	return _TrackerClose(
		p.TraceWrite,
	)
}

func _TrackerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tracker_arm64_bpfel.o
var _TrackerBytes []byte
