// Code generated by bpf2go; DO NOT EDIT.

package collector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type TrackerEventT struct {
	_         structs.HostLayout
	TsNs      uint64
	CgroupId  uint64
	Pid       uint32
	Tid       uint32
	Fd        int32
	DataLen   uint32
	EventType uint8
	Pad       [3]uint8
	Data      [128]int8
	_         [4]byte
}

type TrackerReadArgsT struct {
	_   structs.HostLayout
	Buf uint64
	Fd  int32
	_   [4]byte
}

// LoadTracker returns the embedded CollectionSpec for Tracker.
func LoadTracker() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TrackerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Tracker: %w", err)
	}

	return spec, err
}

// LoadTrackerObjects loads Tracker and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TrackerObjects
//	*TrackerPrograms
//	*TrackerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTrackerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTracker()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TrackerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TrackerSpecs struct {
	TrackerProgramSpecs
	TrackerMapSpecs
	TrackerVariableSpecs
}

// TrackerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TrackerProgramSpecs struct {
	TraceReadEntry   *ebpf.ProgramSpec `ebpf:"trace_read_entry"`
	TraceReadExit    *ebpf.ProgramSpec `ebpf:"trace_read_exit"`
	TraceRecvEntry   *ebpf.ProgramSpec `ebpf:"trace_recv_entry"`
	TraceRecvExit    *ebpf.ProgramSpec `ebpf:"trace_recv_exit"`
	TraceSendtoEntry *ebpf.ProgramSpec `ebpf:"trace_sendto_entry"`
	TraceWriteEntry  *ebpf.ProgramSpec `ebpf:"trace_write_entry"`
}

// TrackerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TrackerMapSpecs struct {
	EventScratch *ebpf.MapSpec `ebpf:"event_scratch"`
	Events       *ebpf.MapSpec `ebpf:"events"`
	PendingReads *ebpf.MapSpec `ebpf:"pending_reads"`
}

// TrackerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TrackerVariableSpecs struct {
}

// TrackerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type TrackerObjects struct {
	TrackerPrograms
	TrackerMaps
	TrackerVariables
}

func (o *TrackerObjects) Close() error {
	return _TrackerClose(
		&o.TrackerPrograms,
		&o.TrackerMaps,
	)
}

// TrackerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type TrackerMaps struct {
	EventScratch *ebpf.Map `ebpf:"event_scratch"`
	Events       *ebpf.Map `ebpf:"events"`
	PendingReads *ebpf.Map `ebpf:"pending_reads"`
}

func (m *TrackerMaps) Close() error {
	return _TrackerClose(
		m.EventScratch,
		m.Events,
		m.PendingReads,
	)
}

// TrackerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type TrackerVariables struct {
}

// TrackerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type TrackerPrograms struct {
	TraceReadEntry   *ebpf.Program `ebpf:"trace_read_entry"`
	TraceReadExit    *ebpf.Program `ebpf:"trace_read_exit"`
	TraceRecvEntry   *ebpf.Program `ebpf:"trace_recv_entry"`
	TraceRecvExit    *ebpf.Program `ebpf:"trace_recv_exit"`
	TraceSendtoEntry *ebpf.Program `ebpf:"trace_sendto_entry"`
	TraceWriteEntry  *ebpf.Program `ebpf:"trace_write_entry"`
}

func (p *TrackerPrograms) Close() error {
	return _TrackerClose(
		p.TraceReadEntry,
		p.TraceReadExit,
		p.TraceRecvEntry,
		p.TraceRecvExit,
		p.TraceSendtoEntry,
		p.TraceWriteEntry,
	)
}

func _TrackerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tracker_bpf.o
var _TrackerBytes []byte
