FROM golang:1.25.3-bookworm AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o heimdall-server ./cmd/server/main.go

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/heimdall-server .

EXPOSE 50051

CMD ["./heimdall-server"]