FROM heimdall-builder AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go generate ./internal/collector

RUN go build -o heimdall-agent ./cmd/agent_test/main.go

FROM debian:bookworm-slim

WORKDIR /root/

COPY --from=builder /app/heimdall-agent .

CMD ["./heimdall-agent"]