// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/sender/log.proto

package sender

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Pid           uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	DurationNs    uint64                 `protobuf:"varint,5,opt,name=duration_ns,json=durationNs,proto3" json:"duration_ns,omitempty"`
	Status        uint32                 `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Method        string                 `protobuf:"bytes,7,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,8,opt,name=path,proto3" json:"path,omitempty"`
	Tid           uint32                 `protobuf:"varint,9,opt,name=tid,proto3" json:"tid,omitempty"`
	Fd            int32                  `protobuf:"zigzag32,10,opt,name=fd,proto3" json:"fd,omitempty"`
	CgroupId      uint64                 `protobuf:"varint,11,opt,name=cgroup_id,json=cgroupId,proto3" json:"cgroup_id,omitempty"`
	Node          string                 `protobuf:"bytes,12,opt,name=node,proto3" json:"node,omitempty"`
	Namespace     string                 `protobuf:"bytes,13,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Pod           string                 `protobuf:"bytes,14,opt,name=pod,proto3" json:"pod,omitempty"`
	Container     string                 `protobuf:"bytes,15,opt,name=container,proto3" json:"container,omitempty"`
	ContainerId   string                 `protobuf:"bytes,16,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_internal_sender_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sender_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_internal_sender_log_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *LogEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LogEntry) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *LogEntry) GetDurationNs() uint64 {
	if x != nil {
		return x.DurationNs
	}
	return 0
}

func (x *LogEntry) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LogEntry) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *LogEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LogEntry) GetTid() uint32 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *LogEntry) GetFd() int32 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *LogEntry) GetCgroupId() uint64 {
	if x != nil {
		return x.CgroupId
	}
	return 0
}

func (x *LogEntry) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *LogEntry) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *LogEntry) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *LogEntry) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *LogEntry) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type LogBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogBatch) Reset() {
	*x = LogBatch{}
	mi := &file_internal_sender_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogBatch) ProtoMessage() {}

func (x *LogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sender_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogBatch.ProtoReflect.Descriptor instead.
func (*LogBatch) Descriptor() ([]byte, []int) {
	return file_internal_sender_log_proto_rawDescGZIP(), []int{1}
}

func (x *LogBatch) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_internal_sender_log_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sender_log_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_internal_sender_log_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_sender_log_proto protoreflect.FileDescriptor

const file_internal_sender_log_proto_rawDesc = "" +
	"\n" +
	"\x19internal/sender/log.proto\x12\x03log\x1a\x1fgoogle/protobuf/timestamp.proto\"\xad\x03\n" +
	"\bLogEntry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\x12\x1f\n" +
	"\vduration_ns\x18\x05 \x01(\x04R\n" +
	"durationNs\x12\x16\n" +
	"\x06status\x18\x06 \x01(\rR\x06status\x12\x16\n" +
	"\x06method\x18\a \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\b \x01(\tR\x04path\x12\x10\n" +
	"\x03tid\x18\t \x01(\rR\x03tid\x12\x0e\n" +
	"\x02fd\x18\n" +
	" \x01(\x11R\x02fd\x12\x1b\n" +
	"\tcgroup_id\x18\v \x01(\x04R\bcgroupId\x12\x12\n" +
	"\x04node\x18\f \x01(\tR\x04node\x12\x1c\n" +
	"\tnamespace\x18\r \x01(\tR\tnamespace\x12\x10\n" +
	"\x03pod\x18\x0e \x01(\tR\x03pod\x12\x1c\n" +
	"\tcontainer\x18\x0f \x01(\tR\tcontainer\x12!\n" +
	"\fcontainer_id\x18\x10 \x01(\tR\vcontainerId\"3\n" +
	"\bLogBatch\x12'\n" +
	"\aentries\x18\x01 \x03(\v2\r.log.LogEntryR\aentries\">\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage26\n" +
	"\n" +
	"LogService\x12(\n" +
	"\bSendLogs\x12\r.log.LogBatch\x1a\r.log.ResponseB/Z-github.com/emresahna/heimdall/internal/senderb\x06proto3"

var (
	file_internal_sender_log_proto_rawDescOnce sync.Once
	file_internal_sender_log_proto_rawDescData []byte
)

func file_internal_sender_log_proto_rawDescGZIP() []byte {
	file_internal_sender_log_proto_rawDescOnce.Do(func() {
		file_internal_sender_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_sender_log_proto_rawDesc), len(file_internal_sender_log_proto_rawDesc)))
	})
	return file_internal_sender_log_proto_rawDescData
}

var file_internal_sender_log_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_sender_log_proto_goTypes = []any{
	(*LogEntry)(nil),              // 0: log.LogEntry
	(*LogBatch)(nil),              // 1: log.LogBatch
	(*Response)(nil),              // 2: log.Response
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_internal_sender_log_proto_depIdxs = []int32{
	3, // 0: log.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: log.LogBatch.entries:type_name -> log.LogEntry
	1, // 2: log.LogService.SendLogs:input_type -> log.LogBatch
	2, // 3: log.LogService.SendLogs:output_type -> log.Response
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_sender_log_proto_init() }
func file_internal_sender_log_proto_init() {
	if File_internal_sender_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_sender_log_proto_rawDesc), len(file_internal_sender_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_sender_log_proto_goTypes,
		DependencyIndexes: file_internal_sender_log_proto_depIdxs,
		MessageInfos:      file_internal_sender_log_proto_msgTypes,
	}.Build()
	File_internal_sender_log_proto = out.File
	file_internal_sender_log_proto_goTypes = nil
	file_internal_sender_log_proto_depIdxs = nil
}
